export default [
    {
        id: 1,   
        img: "/images/1.jpg",
        title: "Create a website using Html CSS and JavaScript",
        price: "10",
        rating: "3",
        location: "Buenos Aires",
        text: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ab eius molestias, quasi, quam omnis magnam impedit hic totam repudiandae reiciendis voluptate inventore nisi quidem.",
    },
    {
        id: 2,     
        img: "/images/2.jpg",
        title: "Complete portfolio website tutorial",
        price: "12",
        rating: "4",
        location: "Cordoba",
        text: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ab eius molestias, quasi, quam omnis magnam impedit hic totam repudiandae reiciendis voluptate inventore nisi quidem.",
    },
    {
        id: 3,
        img: "/images/3.jpg",
        title: "Bootstrap 5 Complete tutorial",
        price: "25",
        rating: "4",
        location: "Rosario",
        text: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ab eius molestias, quasi, quam omnis magnam impedit hic totam repudiandae reiciendis voluptate inventore nisi quidem.",
    },
    {
        id: 4,
        img: "/images/4.jpg",
        title: "UIkit Complete tutorial",
        price: "22",
        rating: "5",
        location: "Mendoza",
        text: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ab eius molestias, quasi, quam omnis magnam impedit hic totam repudiandae reiciendis voluptate inventore nisi quidem.",
    },
    {
        id: 5,
        img: "/images/5.jpg",
        title: "Tailwind CSS card design",
        price: "19",
        rating: "4",
        location: "La Plata",
        text: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ab eius molestias, quasi, quam omnis magnam impedit hic totam repudiandae reiciendis voluptate inventore nisi quidem.",
    },
    {
        id: 6,
        img: "/images/6.jpg",
        title: "Reactjs tutorial for beginner",
        price: "18",
        rating: "4",
        location:"Cordoba",
        text: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ab eius molestias, quasi, quam omnis magnam impedit hic totam repudiandae reiciendis voluptate inventore nisi quidem.",
    },
    {
        id: 7,
        img: "/images/7.jpg",
        title: "Nextjs crash course",
        price: "17",
        rating: "4",
        location:"Buenos Aires",
        text: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ab eius molestias, quasi, quam omnis magnam impedit hic totam repudiandae reiciendis voluptate inventore nisi quidem.",
    },
    {
        id: 8,
        img: "/images/8.jpg",
        title: "Create a website using Tailwind CSS",
        price: "13",
        rating: "3",
        location: "Buenos Aires",
        text: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ab eius molestias, quasi, quam omnis magnam impedit hic totam repudiandae reiciendis voluptate inventore nisi quidem.",
    },
    {
        id: 9,
        img: "/images/9.jpg",
        title: "Create an one page website using ReactJS",
        price: "11",
        rating: "2",
        category: "ReactJS",
        location: "Rosario",
        text: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ab eius molestias, quasi, quam omnis magnam impedit hic totam repudiandae reiciendis voluptate inventore nisi quidem.",
    },
    {
        id: 9,
        img: "/images/9.jpg",
        title: "Create an one page website using ReactJS",
        price: "11",
        rating: "2",
        category: "ReactJS",
        location: "Rosario",
        text: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ab eius molestias, quasi, quam omnis magnam impedit hic totam repudiandae reiciendis voluptate inventore nisi quidem.",
    },
    {
        id: 9,
        img: "/images/9.jpg",
        title: "Create an one page website using ReactJS",
        price: "11",
        rating: "2",
        category: "ReactJS",
        location: "Rosario",
        text: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ab eius molestias, quasi, quam omnis magnam impedit hic totam repudiandae reiciendis voluptate inventore nisi quidem.",
    },
    {
        id: 9,
        img: "/images/9.jpg",
        title: "Create an one page website using ReactJS",
        price: "11",
        rating: "2",
        category: "ReactJS",
        location: "Rosario",
        text: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ab eius molestias, quasi, quam omnis magnam impedit hic totam repudiandae reiciendis voluptate inventore nisi quidem.",
    },
    {
        id: 9,
        img: "/images/9.jpg",
        title: "Create an one page website using ReactJS",
        price: "11",
        rating: "2",
        category: "ReactJS",
        location: "Rosario",
        text: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ab eius molestias, quasi, quam omnis magnam impedit hic totam repudiandae reiciendis voluptate inventore nisi quidem.",
    },
    {
        id: 1,   
        img: "/images/1.jpg",
        title: "Create a website using Html CSS and JavaScript",
        price: "10",
        rating: "3",
        location: "Buenos Aires",
        text: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ab eius molestias, quasi, quam omnis magnam impedit hic totam repudiandae reiciendis voluptate inventore nisi quidem.",
    },
    {
        id: 2,     
        img: "/images/2.jpg",
        title: "Complete portfolio website tutorial",
        price: "12",
        rating: "4",
        location: "Cordoba",
        text: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ab eius molestias, quasi, quam omnis magnam impedit hic totam repudiandae reiciendis voluptate inventore nisi quidem.",
    },
    {
        id: 3,
        img: "/images/3.jpg",
        title: "Bootstrap 5 Complete tutorial",
        price: "25",
        rating: "4",
        location: "Rosario",
        text: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ab eius molestias, quasi, quam omnis magnam impedit hic totam repudiandae reiciendis voluptate inventore nisi quidem.",
    },
    {
        id: 4,
        img: "/images/4.jpg",
        title: "UIkit Complete tutorial",
        price: "22",
        rating: "5",
        location: "Mendoza",
        text: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ab eius molestias, quasi, quam omnis magnam impedit hic totam repudiandae reiciendis voluptate inventore nisi quidem.",
    },
    {
        id: 5,
        img: "/images/5.jpg",
        title: "Tailwind CSS card design",
        price: "19",
        rating: "4",
        location: "La Plata",
        text: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ab eius molestias, quasi, quam omnis magnam impedit hic totam repudiandae reiciendis voluptate inventore nisi quidem.",
    },
    {
        id: 6,
        img: "/images/6.jpg",
        title: "Reactjs tutorial for beginner",
        price: "18",
        rating: "4",
        location:"Cordoba",
        text: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ab eius molestias, quasi, quam omnis magnam impedit hic totam repudiandae reiciendis voluptate inventore nisi quidem.",
    },
    {
        id: 7,
        img: "/images/7.jpg",
        title: "Nextjs crash course",
        price: "17",
        rating: "4",
        location:"Buenos Aires",
        text: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ab eius molestias, quasi, quam omnis magnam impedit hic totam repudiandae reiciendis voluptate inventore nisi quidem.",
    },
    {
        id: 8,
        img: "/images/8.jpg",
        title: "Create a website using Tailwind CSS",
        price: "13",
        rating: "3",
        location: "Buenos Aires",
        text: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ab eius molestias, quasi, quam omnis magnam impedit hic totam repudiandae reiciendis voluptate inventore nisi quidem.",
    },
    {
        id: 9,
        img: "/images/9.jpg",
        title: "Create an one page website using ReactJS",
        price: "11",
        rating: "2",
        category: "ReactJS",
        location: "Rosario",
        text: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ab eius molestias, quasi, quam omnis magnam impedit hic totam repudiandae reiciendis voluptate inventore nisi quidem.",
    },
    {
        id: 9,
        img: "/images/9.jpg",
        title: "Create an one page website using ReactJS",
        price: "11",
        rating: "2",
        category: "ReactJS",
        location: "Rosario",
        text: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ab eius molestias, quasi, quam omnis magnam impedit hic totam repudiandae reiciendis voluptate inventore nisi quidem.",
    },
    {
        id: 9,
        img: "/images/9.jpg",
        title: "Create an one page website using ReactJS",
        price: "11",
        rating: "2",
        category: "ReactJS",
        location: "Rosario",
        text: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ab eius molestias, quasi, quam omnis magnam impedit hic totam repudiandae reiciendis voluptate inventore nisi quidem.",
    },
]
